### ISSUE TITLE
Login screen shows up every time I open GOG Galaxy

### ISSUE THREAD

**Issue by micpp42** [Ertego/gog-galaxy-itch.io#1]
Hi,
I seem to have an issue where every time I open up GOG Galaxy, the itch plugin will prompt me to log in to itch again, instead of remembering the existing login
Thanks

**Comment by lele-blue** [comment]
Fixed in [the last commit](https://github.com/Ertego/gog-galaxy-itch.io/commit/379e9c27026da60fa264a24663ae1c722aa95bed)
(Download at https://github.com/Ertego/gog-galaxy-itch.io/releases/tag/0.0.2)

**Comment by lele-blue** [comment]
(forgot to mention it: thanks for the report and thanks for using my integration, it means a lot to me :) )

**Comment by micpp42** [comment]
No worries... I'd been hoping for an itch.io integration haha. I hope it's OK if I send more reports your way... understand you're just doing this in your free time after all

**Comment by lele-blue** [comment]
Send in as many as you want, i'll do my best to fix them :)
