### ISSUE TITLE
Install instructions? 

### ISSUE THREAD

**Issue by ChildishGiant** [Ertego/gog-galaxy-itch.io#10]
So uhm how do I install this? I've tried putting it in `%localappdata%\GOG.com\Galaxy\plugins\installed` and `%localappdata%\GOG.com\Galaxy\plugins\downloaded` to no joy.

**Comment by Smart123s** [comment]
1. Download the plugin from the releases page.
2. Copy the downloaded ZIP to `C:\Users\USER\AppData\Local\GOG.com\Galaxy\plugins\installed`
3. Unzip
4. (Optional) Delete the zip to save space

source: https://itch.io/t/682012/gog-galaxy-integration

**Comment by lele-blue** [comment]
Yeah using the release zip is essential since the repo does not contain the dependencies (although you could install them via `pip` and the `requirements.txt`, but that might be overwhelming for the average user)
Thanks @Smart123s for the simple tutorial :)

**Comment by ChildishGiant** [comment]
I did install from the releases to there already but no games are showing up

**Comment by Smart123s** [comment]
Do you have any games from itch.io installed?
This integration only shows installed games as of now.

And did you install itch.io to the default location?

Lastly, are you on Windows? I am not sure, if this works with MacOS.

**Comment by lele-blue** [comment]
And additionally, did you connect the integration in GOG Galaxy 2? (i.e. log in to your itch account from GOG Galaxy?)

**Comment by lele-blue** [comment]
As there is no further response, i'll close this issue. Feel free to reopen it if there are any new issues :)
