### ISSUE TITLE
Update version in manifest.json before release

### ISSUE THREAD

**Issue by Slashbunny** [Ertego/gog-galaxy-itch.io#13]
Greetings,

In order to use plugin autoupdate tools like https://github.com/Slashbunny/gog-galaxy-plugin-downloader , the version must be correct in `manifest.json` so it can detect what version of the plugin is installed. 

`manifest.json` has always been set to `0.1`, so it makes version upgrade/detection difficult. 

Thanks!

**Comment by lele-blue** [comment]
Will do, however the latest release was just a RC which was not meant to be used and just for testing purposes.
