### ISSUE TITLE
Simplified location in step 2 is incorrect

### ISSUE THREAD

**Issue by WebDev9000** [Ertego/gog-galaxy-itch.io#14]
Looks like 3 days ago the path in step 2 was simplified to:

`%LOCALAPPDATA%\AppData\Local\GOG.com\Galaxy\plugins\installed`

However, this is incorrect.  It should be:

`%LOCALAPPDATA%\GOG.com\Galaxy\plugins\installed`

Otherwise the \AppData\Local\ is redundant.

**Comment by lele-blue** [comment]
Thanks for the heads up, you're right.
I fixed it in the readme
