### ISSUE TITLE
Integration crashing

### ISSUE THREAD

**Issue by ghost** [Ertego/gog-galaxy-itch.io#15]
I have installed both through zip and github to fix the issue as well as using different versions of the integration.

**Comment by lele-blue** [comment]
Can you please attach the logfile of the plugin (The files with itch in the name located at `C:\ProgramData\GOG.COM\Galaxy\logs`)?

**Comment by wassh1** [comment]
I probably have the same error:
[plugin-itch-fd0effe6-77d9-42bc-999d-a5a5c870c2a4.log](https://github.com/Ertego/gog-galaxy-itch.io/files/4460322/plugin-itch-fd0effe6-77d9-42bc-999d-a5a5c870c2a4.log)

**Comment by lele-blue** [comment]
The error found in your log is a
`sqlite3.OperationalError: unable to open database file`.
Do you have the itch client installed?

**Comment by wassh1** [comment]
I had an old version of the itch client installed. Now it is updated to the newest version. Then I reconnected Galaxy to itch.
After that the plugin is working.

**Comment by lele-blue** [comment]
Glad to hear that :)
I'll close this issue since it's resolved
