### ISSUE TITLE
Plugin crashing

### ISSUE THREAD

**Issue by StarKitsune** [Ertego/gog-galaxy-itch.io#16]
Every time I attempt to connect the integration, it crashes, giving me "ModuleNotFoundError: No module named 'aiohttp'." Any help would be appreciated.
[plugin-itch-fd0effe6-77d9-42bc-999d-a5a5c870c2a4.log](https://github.com/Ertego/gog-galaxy-itch.io/files/4496008/plugin-itch-fd0effe6-77d9-42bc-999d-a5a5c870c2a4.log)

**Comment by lele-blue** [comment]
Did you install the release version (i.e. not using the download as zip feature of github)?

**Comment by StarKitsune** [comment]
Looks like I just can't read, thanks, that solved it.

**Comment by lele-blue** [comment]
No problem, I'm glad I could help :)
