### ISSUE TITLE
Download Metadata and "cover"

### ISSUE THREAD

**Issue by Berbils** [Ertego/gog-galaxy-itch.io#17]
When a itch.io game is in Galaxy, there is no Metadata aside from name. There is usually some form of image cover and metadata attached to the page. I've attached screenshots from Playnite which does the basic idea of what I'm going for. 
![cover](https://user-images.githubusercontent.com/17146279/81192822-471ead00-8f80-11ea-9fc0-db8094a35df1.png)
![metadata](https://user-images.githubusercontent.com/17146279/81192824-47b74380-8f80-11ea-8deb-8324c1c7dabc.png)

**Comment by lele-blue** [comment]
The Metadata is created by GOG Galaxy based on the name the integration provides. If GOG doesn't find a matching GamesDB entry, it won't display a cover image.
Unfortunately, there's nothing the integration can do to hint or provide metadata aside from the name.

**Comment by Bobcat90** [comment]
@IrritatedGoat If there's no metadata then I think that means the game doesn't have an entry on IGDB (which is what GOG uses), so you can always add the game and its details there yourself.
