### ISSUE TITLE
Not showing games

### ISSUE THREAD

**Issue by SuperBlazer505** [Ertego/gog-galaxy-itch.io#18]
My itch.io account apparently connects, but it doesn't show any games.

**Comment by lele-blue** [comment]
Do you have the itch client installed?

**Comment by SuperBlazer505** [comment]
Yes, I do.

**Comment by lele-blue** [comment]
In that case, can you please attach the logfile?

**Comment by SuperBlazer505** [comment]
I'm not sure which file is that supposed to be, please correct me if I sent the wrong one.
[plugin-itch-fd0effe6-77d9-42bc-999d-a5a5c870c2a4.log](https://github.com/Ertego/gog-galaxy-itch.io/files/4592881/plugin-itch-fd0effe6-77d9-42bc-999d-a5a5c870c2a4.log)

**Comment by lele-blue** [comment]
The integration seems to find some games, but thinks they are just cached.
That was a bug in the previous version that has since been fixed, on what version are you?

**Comment by imsys** [comment]
@SuperBlazer505, It lists only installed games. If you just installed itch, it will not show anything until you install games through their app.

**Comment by SuperBlazer505** [comment]
Oh, OK, I wasn't aware of it because other plugins show all games. Thanks for clearing that up.

**Comment by lele-blue** [comment]
That however is definitely planned as a feature, but it depends on #6 to be resolved first, which would more or less require a complete rewrite.
I will tackle this after my high school graduation(in ~4 Weeks), I don't have enough time at the moment :/.

**Comment by SuperBlazer505** [comment]
Cool, best of luck with graduation tests!
