### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by 5kel** [Ertego/gog-galaxy-itch.io#20]
whenever i try to link my itch.io account the plugin crashes

**Comment by lele-blue** [comment]
do you have the itch client installed?

**Comment by 5kel** [comment]
o
no i dont lol

Am Mi., 13. Mai 2020 um 00:21 Uhr schrieb David Eichelsdörfer <
notifications@github.com>:

**Comment by 5kel** [comment]
so i just installed it but the plugin still crashes when trying to link-

Am Mi., 13. Mai 2020 um 09:05 Uhr schrieb Skelmoor <skelmoor@gmail.com>:

**Comment by lele-blue** [comment]
can you please attach the log file of the integration?

**Comment by 5kel** [comment]
where can i find thar?

Am Mi., 13. Mai 2020 um 19:51 Uhr schrieb David Eichelsdörfer <
notifications@github.com>:

**Comment by lele-blue** [comment]
It's a file starting with 'itch' in C:\ProgramData\Gog.com\Galaxy\logs

**Comment by lele-blue** [comment]
As there is no further action in this issue, i'll close it.
Feel free to reopen it at any time if the issue arises again ;)
