### ISSUE TITLE
No change in GOG?

### ISSUE THREAD

**Issue by ruthm982** [Ertego/gog-galaxy-itch.io#21]
Hi,

I've installed the plug in by unzipping the folder from the release page into the path given, but nothing has changed within GOG - there's no way to log in to my itch account, and searching for the plugin has no results? 

The Itch launcher and GOG Galaxy are both installed in C as default.

Thanks!

**Comment by lele-blue** [comment]
Is the "itch" folder inside the "installed" folder?

**Comment by ruthm982** [comment]
Never mind! Just had to turn it off and on again. A full restart of GOG Galaxy prompted the "login to itch" when I started it up again, and it now seems to be fine and I can see my installed games as expected. Thank you!

**Comment by lele-blue** [comment]
Glad I could help :)
