### ISSUE TITLE
No Results

### ISSUE THREAD

**Issue by Darxide23** [Ertego/gog-galaxy-itch.io#24]
After connecting I just get "no results" in the Galaxy client for Itch.io. It was this way when I first tried several months ago and i just assumed it wasn't working right at the time. Now there have been a couple more updates and it still isn't working for me.

**Comment by lele-blue** [comment]
Did you install any games through the itch client?

**Comment by antoineguillou** [comment]
hi, same issue here, i own some games on itch.io but nothing appears in the itch tab on Galaxy. Only installed games appear in the "owned games" filter

**Comment by Zobrob** [comment]
I have the same issue. So does it only show installed games and not the ones in the library?

**Comment by lele-blue** [comment]
As there was no additional response, i'll close this issue. Feel free to reopen it at any time if the problem still persists :)
