### ISSUE TITLE
Wishing Sarah not launching (error message)

### ISSUE THREAD

**Issue by MarkoH01** [Ertego/gog-galaxy-itch.io#25]
When I try to launch "Wishing Sarah" in Galaxy I get the error message that "TinySarah.exe" cannot be found even though it is there. Launches fine directly in the itch client or when I double click the exe.

**Comment by lele-blue** [comment]
Are other games working?

**Comment by lele-blue** [comment]
As there was no additional response, i'll close this issue. Feel free to reopen it at any time if the problem still persists :)
