### ISSUE TITLE
the plugin keeps crashing 

### ISSUE THREAD

**Issue by bara9880** [Ertego/gog-galaxy-itch.io#27]
![image](https://user-images.githubusercontent.com/58350309/84547757-d439ec00-ad0c-11ea-8214-20d169854a68.png)

**Comment by lele-blue** [comment]
Can you please attach the log file of the plugin?

**Comment by bara9880** [comment]
how can i do that ?

**Comment by lele-blue** [comment]
It's a file with 'itch' in its name at `C:\ProgramData\GOG.COM\Galaxy\logs`

**Comment by bara9880** [comment]
nvm i found the issue , i had the wrong file in place 😅
thanks for the help !

**Comment by lele-blue** [comment]
glad it works now ^^
