### ISSUE TITLE
Plugin has crashed.

### ISSUE THREAD

**Issue by SlipSlot** [Ertego/gog-galaxy-itch.io#28]
No error or explanation. Retrying gives the same error. This is before I could even sign in to itch.

https://prnt.sc/t0qa8j

**Comment by lele-blue** [comment]
Can you please attach the logfile of the plugin?

**Comment by SlipSlot** [comment]
Looks like it was my error, didn't download from the repos like advised.

**Comment by lele-blue** [comment]
Is everything working then?
