### ISSUE TITLE
Doesn't add game(s)

### ISSUE THREAD

**Issue by riku55** [Ertego/gog-galaxy-itch.io#3]
So I only own one game on itch.io (Escaped Chasm) but it doesn't show up using the integration.
I used the standard path for installing the itch.io app( AppData -> Local) and completed the login. Though I'm on Windows 7, might that be an issue?
Looking at the log, owned_games and local_games both return an empty list.

[plugin-itch-fd0effe6-77d9-42bc-999d-a5a5c870c2a4 - Kopie.txt](https://github.com/Ertego/gog-galaxy-itch.io/files/3682103/plugin-itch-fd0effe6-77d9-42bc-999d-a5a5c870c2a4.-.Kopie.txt)

**Comment by peldas** [comment]
I have the same issue; I have 35 games on Itch with only one installed, but none of them show up with the integration. I'm on Windows 10 Home Home 64-bit with the latest Galaxy 2.0.7 client installed.

**Comment by lele-blue** [comment]
The integration is currently only able to show games downloaded through the itch client.
I'll add support for installing/displaying bought games in the near future though.
@kelpso: regarding your issue with the one game installed: can you replace your itch.py with the latest one from this repo and attach the log file generated after reproducing the bug to this issue?

**Comment by peldas** [comment]
@Ertego Never mind, I just noticed the game that the Itch client was telling me was "installed" actually had no files on disk; I installed another game and it works perfectly now. Thanks for your efforts, can't wait for it to show the library in the future :)

**Comment by riku55** [comment]
Oh ok, didn't know that. Installe the game and it's working now :)

**Comment by lele-blue** [comment]
Glad to hear it's working :D
I should probably communicate it's current limits through the readme.
However thanks for the issues and using the integration :)
