### ISSUE TITLE
Plugin does not sync and does not disconnect

### ISSUE THREAD

**Issue by Danyelalejandro** [Ertego/gog-galaxy-itch.io#30]
It does not sync new added games and does not disconnect in order to refresh them either.

**Comment by Danyelalejandro** [comment]
right now appears as offline and does not allow to disconnect

**Comment by lele-blue** [comment]
Have you installed any games through the itch client?

**Comment by lele-blue** [comment]
As there was no additional response, i'll close this issue. Feel free to reopen it at any time if the problem still persists :)

**Comment by Danyelalejandro** [comment]
Sorry, didn't see your comment. No. I haven't installed anything and still is always offline and does not sync anymore

**Comment by lele-blue** [comment]
can you attach the log?

**Comment by Danyelalejandro** [comment]
Yes, of course. Thank you so much.
[plugin-itch-2df02142-4d8a-4a4b-9b6e-c3a0bc62f93b.log.zip](https://github.com/Ertego/gog-galaxy-itch.io/files/4919231/plugin-itch-2df02142-4d8a-4a4b-9b6e-c3a0bc62f93b.log.zip)

**Comment by lele-blue** [comment]
These logs don't seem to be from this plugin, as the uuids don't match and I also don't recognize any characteristic log messages from my code in them :/

**Comment by Danyelalejandro** [comment]
[plugin-itch-74f1b442-9501-4237-a57b-53733d3e07e7.log](https://github.com/Ertego/gog-galaxy-itch.io/files/4925935/plugin-itch-74f1b442-9501-4237-a57b-53733d3e07e7.log)
Sorry, please check this one. Thank you

**Comment by lele-blue** [comment]
Still can't be the right one as it mentions errors in files called "main.py" and "plugin.py", but this code has neither of those (everything is in a "itch.py")
