### ISSUE TITLE
Plugin has crashed?

### ISSUE THREAD

**Issue by Daxi04** [Ertego/gog-galaxy-itch.io#35]
![Crashed](https://user-images.githubusercontent.com/79226473/108264260-97f63f80-7167-11eb-94cd-fee0251c6b1d.png)

I don't know what's the problem. I tried it more times, but still the same problem.

**Comment by lele-blue** [comment]
Did you download the plugin from the releases page or did you use the download button on the main page?
If the former is the case, please attach the log file to this report!

**Comment by Daxi04** [comment]
I downloaded it from the main page before, than I downloaded from the releases page and it works. Thank you.

**Comment by lele-blue** [comment]
Glad to hear that
