### ISSUE TITLE
Tooltip on games not showing itch logo

### ISSUE THREAD

**Issue by micpp42** [Ertego/gog-galaxy-itch.io#4]
With the other integrations I've got installed, hovering over a game shows the logo of the platform and the name of the game. With the itch integration, it just shows the name of the game, with a blank space in place of where the logo would go.

**Comment by lele-blue** [comment]
Thats a gog issue described [here](https://github.com/gogcom/galaxy-integrations-python-api/issues/26), i'll put this issue on hold until it's resolved

**Comment by micpp42** [comment]
This one was fixed by a GOG update
